### ISSUE TITLE
Fix type defs for .with() and .clone()

### ISSUE THREAD

**Issue by dbushong** [groupon/gofer#104]
The return values for https://github.com/groupon/gofer/blob/02c190f6439ffaf86050a3a58e8518bf8b64cdfc/lib/typedefs.d.ts#L23-L25 shouldn't be `Gofer` - they should be whatever the subclass is - I'm not sure how to properly declare this in typescript

**Comment by jkrems** [comment]
There's the magical `this` annotation that may help.

<img width="438" alt="Screen Shot 2019-10-05 at 10 52 30 AM" src="https://user-images.githubusercontent.com/567540/66258799-4f023e80-e75e-11e9-8ee5-ef359a4a1829.png">

[Playground Link](https://www.typescriptlang.org/play/#code/MYGwhgzhAEDiD2AzApgJ2gbwFDV9A7gJYAuAFgBTwAOxh8AdhAFzRj0CeAlC2YTNnkHRUyYgFdU9aLwgBuHHgC+WZVlCQYsEqTEAjAMIhCyesWjIAHsRMATTUjSYVWNQwhmA5qWgBeaPWR8OG09Q2NTck4AOiIycgxFTnkgA)

**Comment by dbushong** [comment]
Thanks!  I saw the `this` syntax, but assumed it meant you had to be returning the exact same object - but I guess it really doesn't matter from a typing perspective - at least at the level of detail we're currently using.
