### ISSUE TITLE
request sunsetting

### ISSUE THREAD

**Issue by g-patel** [groupon/gofer#114]
Not filing an issue per say, rather more of my own curiosity on what sunsetting of [request](https://github.com/request/request/issues/3142) library this means for gofer? I loved gofer.

**Comment by jkrems** [comment]
The good news is: As of version 3 of `gofer`, it no longer uses request (https://github.com/groupon/gofer/blob/master/BREAKING_v3.md). So hopefully it should just continue to work. :)

**Comment by g-patel** [comment]
Thanks for reply. @jkrems you look still active on maintaining this good library. :) 🙌 

That's great. Long Live gofer! Certainly didn't look at the V3 doc before commenting here.
