### ISSUE TITLE
Add an early error if timeout or connectTimeout are not numbers

### ISSUE THREAD

**Issue by jkrems** [groupon/gofer#26]
Since request sends the request on nextTick, it's almost impossible to find out what triggered the `TypeError` otherwise.

**Comment by johan** [comment]
:+1: – just a (bunch of?) well-worded `throw`(s) on parameters of known-bad types sounds nice.

**Comment by jkrems** [comment]
Alternative would be to do what we do for headers - there we just remove undefined/null headers. We could also auto-correct timeout values like `"1000"` to `1000`.

**Comment by johan** [comment]
My gut feel is it's better to require strictly correct inputs, rather than trying to be friendly. If some cson config says `timeout: '30 * 1000'` instead of `timeout: 30 * 1000` for instance, the auto correction might either still fail, or silently produce 30ms instead of 30s.

**Comment by jkrems** [comment]
I just don't want to crash people's apps that worked fine before (because they are running node 0.10). And I'd prefer not bumping the major of gofer because there's a pretty big long tail of changes to propagate such a bump.

**Comment by jkrems** [comment]
P.S.: For your example, the auto-correct I had in mind would produce NaN:

```
> +'30 * 1000'
NaN
> +'1000'
1000
```

The plan would be: auto-correct and warn if NODE_ENV != production. E.g. `if typeof timeout != number then timeout = +timeout && warn("Timeout %j isn't a number, using %j", timeout, +timeout)`
